# -*- coding: utf-8 -*-
"""RandomForestMelbourne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ALcMRO5zuHZPqWT-Dzz5YNJ60MTSyTD

<h1>Random Forest Regressor

Neste notebook, Matheus aplicará o algorítmo Random Forest Regressor ao dataset de Melbourne
"""

#Montando o Drive
from google.colab import drive
drive.mount('/content/drive')

#Importação e leitura dos dados
import pandas as pd
melbourne = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data_csv/melb_data.csv')

#Analizando as colunas
print(melbourne.dtypes)
melbourne_filt = melbourne.dropna(axis = 0)
print(list(melbourne))

#Crição de Atributos
y = melbourne_filt['Price']
atributos = ['Rooms', 'Bathroom', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude']
x = melbourne_filt[atributos]

"""<h3>Aplicação do Algoritmo Random Forest"""

#O algoritmo foi criado
from sklearn.ensemble import RandomForestRegressor
melbourne_model = RandomForestRegressor()
melbourne_model.fit(x, y)

"""<h3>Criação de Previsões"""

from sklearn.model_selection import train_test_split
#Split data into training and validation data, for both features and target
#The split is based on a random number generator. Supplying a numeric value to
#The random_state argument guarantees we get the same split every time we
#Run the Script
train_x, val_x, train_y, val_y = train_test_split(x, y, random_state = 0)
melbourne_model = RandomForestRegressor()
print('O algoritmo foi criado!')
melbourne_model.fit(train_x, train_y)

from sklearn.metrics import mean_absolute_error
#Predição
pred = melbourne_model.predict(val_x)
print(mean_absolute_error(val_y, pred))

"""Este modelo (RandomForestRegressor) se saiu melhor para avaliar esta situção do que DecisionTreeRegressor. Este obteve MAE de 191958, enquanto DecisionTreeRegressor, 262978."""